node {
     
     withMaven(maven:'maven') {
	
	 stage('Checking Env var') {
		  sh 'echo "$JAVA_HOME"
		  sh 'pwd'
      	     }  
	 stage('Checkout code') {
		  sh 'date'
		  sh 'pwd'
      		  checkout scm
		  sh 'git log -n 1'		
	    }
		
	stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Image') {
           dir ('account-service') {
           def app = docker.build "localhost:5000/account-service:${env.version}"
           app.push()
            }
        }

        stage ('Run') {
           docker.image("localhost:5000/account-service:${env.version}").run('-p 2222:2222 -h account --name account --link discovery')
        }	
         
    }
}
